apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
  namespace: default
  labels:
    app: busybox-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi